import ApiTable from "../docs/api_table";
import CodeExample from "../docs/code_example";
import DemoSection from "../docs/demo_section";
import DocPage from "../docs/doc_page";

const colors = [
  "primary",
  "accent",
  "success",
  "info",
  "warning",
  "danger",
  "default",
];

const tableCode = (
  tokens?: string,
) => `<table data-table${tokens ? `="${tokens}"` : ""}>
  <caption>Food details</caption>
  <thead>
    <tr>
      <th scope="col">Type of food</th>
      <th scope="col">Calories</th>
      <th scope="col">Average price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td data-label="Type of food">Slice of pizza</td>
      <td data-label="Calories">450</td>
      <td data-label="Average price">$5.00</td>
    </tr>
    <tr>
      <td data-label="Type of food">Hamburger</td>
      <td data-label="Calories">350</td>
      <td data-label="Average price">$3.50</td>
    </tr>
  </tbody>
</table>`;

const tableRows = [
  {
    name: "data-label",
    type: "td attribute",
    defaultValue: "Absent",
    description:
      "Provides the visible mobile label generated by the responsive table CSS.",
  },
  {
    name: "data-table",
    type: "Table attribute",
    defaultValue: "Absent",
    description:
      "Its presence enables responsive table behavior. It accepts primary, accent, success, info, warning, danger or default for a semantic tone, plus compact for 0.5rem cell padding and border for internal body-cell separators. Tokens compose in any order.",
  },
];

const Table = ({ tokens }: { tokens?: string }) => {
  const attributes = {
    "data-table": typeof tokens === "string" ? tokens : "",
  };

  return (
    <table {...attributes} data-markdown="exclude">
      <caption>Food details</caption>
      <thead>
        <tr>
          <th scope="col">Type of food</th>
          <th scope="col">Calories</th>
          <th scope="col">Average price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td data-label="Type of food">Slice of pizza</td>
          <td data-label="Calories">450</td>
          <td data-label="Average price">$5.00</td>
        </tr>
        <tr>
          <td data-label="Type of food">Hamburger</td>
          <td data-label="Calories">350</td>
          <td data-label="Average price">$3.50</td>
        </tr>
      </tbody>
    </table>
  );
};

export default () => (
  <DocPage page="Tables">
    <DemoSection id="responsive-table" title="Responsive table">
      <p>
        Below 800px, each <code>data-label</code> value becomes the visible
        heading for its cell.
      </p>
      <Table />
      <CodeExample code={tableCode()} />
    </DemoSection>

    <DemoSection id="table-colors" title="Table colors">
      <p>
        Set data-table to a semantic color token to apply that tone to the
        responsive table. Dragonglass supports primary, accent, success, info,
        warning, danger, and default.
      </p>
      {colors.map((color) => (
        <div>
          <Table tokens={color} />
          <CodeExample code={tableCode(color)} />
        </div>
      ))}
    </DemoSection>

    <DemoSection
      id="table-spacing-and-borders"
      title="Compact spacing and internal borders"
    >
      <p>
        Add <code>compact</code> to set <code>0.5rem</code> padding on the
        caption, column headers, and cells. The compact spacing remains in
        effect when the table switches to its responsive presentation.
      </p>
      <p>
        Add <code>border</code> to draw separators only between body cells. The
        separators follow the selected semantic color family. Without a color
        token, they use the default border color.
      </p>
      <p>
        Tokens compose in any order. This example combines the primary tone with
        compact spacing and internal separators.
      </p>
      <Table tokens="primary compact border" />
      <CodeExample code={tableCode("primary compact border")} />
    </DemoSection>

    <DemoSection id="table-api" title="Table API">
      <ApiTable caption="Responsive table attributes" rows={tableRows} />
    </DemoSection>
  </DocPage>
);
