import ApiTable from "../docs/api_table";
import CodeExample from "../docs/code_example";
import DemoSection from "../docs/demo_section";
import DocPage from "../docs/doc_page";

const colors = [
  "primary",
  "accent",
  "success",
  "info",
  "warning",
  "danger",
  "default",
];

const tableCode = (
  color?: string,
) => `<table${color ? ` data-table="${color}"` : ""}>
  <caption>Food details</caption>
  <thead>
    <tr>
      <th scope="col">Type of food</th>
      <th scope="col">Calories</th>
      <th scope="col">Average price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td data-label="Type of food">Slice of pizza</td>
      <td data-label="Calories">450</td>
      <td data-label="Average price">$5.00</td>
    </tr>
    <tr>
      <td data-label="Type of food">Hamburger</td>
      <td data-label="Calories">350</td>
      <td data-label="Average price">$3.50</td>
    </tr>
  </tbody>
</table>`;

const tableRows = [
  {
    name: "caption",
    type: "Table element",
    defaultValue: "Required for these examples",
    description: "Names the table for readers and assistive technology.",
  },
  {
    name: "scope=col",
    type: "th attribute",
    defaultValue: "Column header",
    description: "Associates each heading with the cells in its column.",
  },
  {
    name: "data-label",
    type: "td attribute",
    defaultValue: "Matching column heading",
    description:
      "Provides the visible mobile label generated by the responsive table CSS.",
  },
  {
    name: "data-table",
    type: "Table attribute",
    defaultValue: "Uncolored table",
    description:
      "Accepts primary, accent, success, info, warning, danger or default.",
  },
];

const Table = ({ color }: { color?: string }) => {
  const attributes = color ? { "data-table": color } : {};

  return (
    <table {...attributes}>
      <caption>Food details</caption>
      <thead>
        <tr>
          <th scope="col">Type of food</th>
          <th scope="col">Calories</th>
          <th scope="col">Average price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td data-label="Type of food">Slice of pizza</td>
          <td data-label="Calories">450</td>
          <td data-label="Average price">$5.00</td>
        </tr>
        <tr>
          <td data-label="Type of food">Hamburger</td>
          <td data-label="Calories">350</td>
          <td data-label="Average price">$3.50</td>
        </tr>
      </tbody>
    </table>
  );
};

export default () => (
  <DocPage page="Tables">
    <DemoSection id="responsive-table" title="Responsive table">
      <p>
        Below 800px, each <code>data-label</code> value becomes the visible
        heading for its cell.
      </p>
      <Table />
      <CodeExample code={tableCode()} />
    </DemoSection>

    <DemoSection id="table-colors" title="Table colors">
      {colors.map((color) => (
        <div>
          <Table color={color} />
          <CodeExample code={tableCode(color)} />
        </div>
      ))}
    </DemoSection>

    <DemoSection id="table-api" title="Table API">
      <ApiTable caption="Responsive table attributes" rows={tableRows} />
    </DemoSection>

    <DemoSection
      id="table-accessibility"
      title="Accessibility and common errors"
    >
      <ul>
        <li>
          Keep a descriptive <code>caption</code> and use{" "}
          <code>scope="col"</code>
          on every column header.
        </li>
        <li>
          Make each <code>data-label</code> match its column heading exactly so
          the compact layout preserves the same meaning.
        </li>
        <li>
          Do not use a table only for visual alignment. Use it when rows and
          columns describe real data relationships.
        </li>
        <li>
          The current responsive CSS hides <code>thead</code> visually. The
          semantic headers remain in the markup, while data labels provide the
          compact visual headings.
        </li>
      </ul>
    </DemoSection>
  </DocPage>
);
